# Generated by Django 2.1.14 on 2019-11-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0041_auto_20191119_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='IsOnline',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='Remark',
            field=models.TextField(max_length=500, null=True, verbose_name='备注'),
        ),
    ]
