# Generated by Django 2.1.14 on 2019-11-21 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0050_auto_20191121_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualbrushmission',
            name='EffectTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='生效日期'),
            preserve_default=False,
        ),
    ]
