# Generated by Django 2.1.14 on 2019-11-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0072_taobaosession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taobaosession',
            old_name='Exit_Date',
            new_name='Ext_Date',
        ),
        migrations.RenameField(
            model_name='taobaosession',
            old_name='Exit_Time',
            new_name='Ext_Time',
        ),
    ]
