# Generated by Django 2.1.14 on 2019-11-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0034_auto_20191118_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceNumberMissionKeywordClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=150, verbose_name='养号任务关键字类别')),
            ],
        ),
        migrations.RemoveField(
            model_name='maintenancenumbermissionkeyword',
            name='Owner',
        ),
        migrations.AlterField(
            model_name='maintenancenumbermissionkeyword',
            name='Name',
            field=models.TextField(max_length=150, verbose_name='养号任务关键字'),
        ),
        migrations.AddField(
            model_name='maintenancenumbermissionkeyword',
            name='Classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.MaintenanceNumberMissionKeywordClassification', verbose_name='类别'),
        ),
    ]
