# Generated by Django 2.1.14 on 2019-11-16 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0027_auto_20191116_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceNumberMissionKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=150, verbose_name='视频分类名')),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
        ),
        migrations.RemoveField(
            model_name='maintenancenumbermission',
            name='VideoClassifications',
        ),
        migrations.AddField(
            model_name='maintenancenumbermission',
            name='KeywordClassifications',
            field=models.ManyToManyField(to='Web.MaintenanceNumberMissionKeyword'),
        ),
    ]
