# Generated by Django 2.1.14 on 2019-11-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_auto_20191111_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='pic',
            new_name='Pic',
        ),
    ]
