# Generated by Django 2.1.14 on 2019-11-09 18:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=150, verbose_name='商品分类名')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=150, verbose_name='标题')),
                ('OutSidePlatformID', models.TextField(max_length=150, verbose_name='外部ID')),
                ('Price', models.TextField(max_length=150, null=True, verbose_name='售价')),
                ('Sales', models.TextField(max_length=150, null=True, verbose_name='销量')),
                ('OutSidePlatformURL', models.TextField(max_length=150, null=True, verbose_name='外部URL')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMEI', models.TextField(max_length=150, verbose_name='IMEI码')),
                ('SysID', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='GUID')),
            ],
        ),
        migrations.CreateModel(
            name='TikTokAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.TextField(max_length=150, null=True, verbose_name='抖音UID')),
                ('NickName', models.TextField(max_length=150, null=True, verbose_name='昵称')),
                ('TikTokID', models.TextField(max_length=150, null=True, verbose_name='抖音号')),
                ('Describe', models.TextField(max_length=150, null=True, verbose_name='描述')),
                ('Attention', models.IntegerField(default=0, verbose_name='关注')),
                ('Fans', models.IntegerField(default=0, verbose_name='粉丝')),
                ('Praise', models.IntegerField(default=0, verbose_name='赞')),
                ('Video', models.IntegerField(default=0, verbose_name='作品数')),
                ('NumOfPraiseToOther', models.IntegerField(default=0, verbose_name='喜欢')),
                ('ShareURL', models.TextField(max_length=150, null=True, verbose_name='短链接')),
                ('ShowWindowExists', models.BooleanField(default=False, verbose_name='窗口是否显示')),
            ],
        ),
        migrations.CreateModel(
            name='WorkClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=150, verbose_name='视频分类名')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShareURL', models.TextField(max_length=150, null=True, verbose_name='短链接')),
                ('VideoID', models.TextField(max_length=150, null=True, verbose_name='视频ID')),
                ('NumOfPraiseGet', models.IntegerField(default=0, verbose_name='喜欢')),
                ('NumOfComments', models.IntegerField(default=0, verbose_name='评论')),
                ('NumOfShare', models.IntegerField(default=0, verbose_name='分享')),
                ('TikTokAccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.TikTokAccount', verbose_name='作者')),
            ],
        ),
        migrations.AddField(
            model_name='workclassification',
            name='Works',
            field=models.ManyToManyField(to='Web.Works'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='TikTokAccountID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.TikTokAccount', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='goodclassification',
            name='Goods',
            field=models.ManyToManyField(to='Web.Goods'),
        ),
    ]
