# Generated by Django 2.1.14 on 2019-11-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20191109_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokaccount',
            name='UpdateTime',
            field=models.DateTimeField(null=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='works',
            name='UpdateTime',
            field=models.DateTimeField(null=True, verbose_name='更新日期'),
        ),
    ]
