# Generated by Django 2.1.14 on 2019-11-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_auto_20191112_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodclassification',
            name='Goods',
        ),
        migrations.RemoveField(
            model_name='workclassification',
            name='Works',
        ),
        migrations.AddField(
            model_name='goods',
            name='GoodClassifications',
            field=models.ManyToManyField(to='Web.GoodClassification'),
        ),
        migrations.AddField(
            model_name='works',
            name='WorkClassifications',
            field=models.ManyToManyField(to='Web.WorkClassification'),
        ),
    ]
