# Generated by Django 2.1.14 on 2019-11-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0013_videos_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilephone',
            old_name='TikTokAccountID',
            new_name='TikTokAccount',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='MobilePhoneID',
            new_name='MobilePhone',
        ),
        migrations.RenameField(
            model_name='works',
            old_name='TikTokAccountID',
            new_name='TikTokAccount',
        ),
        migrations.RemoveField(
            model_name='works',
            name='VideoID',
        ),
        migrations.AddField(
            model_name='works',
            name='Video',
            field=models.TextField(max_length=150, null=True, verbose_name='视频ID'),
        ),
    ]
