# Generated by Django 2.1.14 on 2019-11-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0014_auto_20191114_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='Video',
            new_name='VideoID',
        ),
    ]
