# Generated by Django 2.1.14 on 2019-11-14 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0015_auto_20191114_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokaccount',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskType',
            field=models.IntegerField(choices=[(1, '上传视频'), (2, '互刷任务'), (3, '养号任务'), (4, '刷粉任务'), (5, '关注任务')], default=1, verbose_name='类型'),
        ),
    ]
