# Generated by Django 2.1.14 on 2019-11-16 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0028_auto_20191116_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelAndPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserSystemPercent', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='顶级用户提成')),
                ('UserALevelPercent', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='上级用户提成')),
                ('UserBLevelPercent', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='上上级用户提成')),
                ('Subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subscriber', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('UserALevel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserALevel', to=settings.AUTH_USER_MODEL, verbose_name='上级用户')),
                ('UserBLevel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserBLevel', to=settings.AUTH_USER_MODEL, verbose_name='上上级用户')),
                ('UserSystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserSystem', to=settings.AUTH_USER_MODEL, verbose_name='顶级用户')),
            ],
        ),
    ]
