# Generated by Django 2.1.14 on 2019-11-16 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0029_levelandpercent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LevelAndPercent',
            new_name='Agent',
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='Agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.Agent', verbose_name='代理'),
        ),
    ]
