# Generated by Django 2.1.14 on 2019-11-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0035_auto_20191118_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancenumbermission',
            old_name='KeywordClassifications',
            new_name='Keyword',
        ),
    ]
