# Generated by Django 2.1.14 on 2019-11-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0036_auto_20191118_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancenumbermissionkeyword',
            name='Classification',
        ),
        migrations.AddField(
            model_name='maintenancenumbermissionkeyword',
            name='Classification',
            field=models.ManyToManyField(to='Web.MaintenanceNumberMissionKeywordClassification'),
        ),
    ]
