# Generated by Django 2.1.14 on 2019-11-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0037_auto_20191118_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancenumbermissionkeyword',
            name='Classification',
        ),
        migrations.AddField(
            model_name='maintenancenumbermissionkeyword',
            name='Classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.MaintenanceNumberMissionKeywordClassification', verbose_name='类别'),
        ),
    ]
