# Generated by Django 2.1.14 on 2019-11-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0043_auto_20191120_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokaccount',
            name='Classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.MaintenanceNumberMissionKeywordClassification', verbose_name='标签'),
        ),
    ]
