# Generated by Django 2.1.14 on 2019-11-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0044_auto_20191120_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='HeartBeat',
            field=models.DateTimeField(auto_now=True, verbose_name='心跳时间'),
        ),
    ]
