# Generated by Django 2.1.14 on 2019-11-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0051_mutualbrushmission_effecttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokaccount',
            name='IsOnline',
        ),
    ]
