# Generated by Django 2.1.14 on 2019-11-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0057_auto_20191122_2134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Config',
            new_name='SystemConfig',
        ),
        migrations.AlterField(
            model_name='followmission',
            name='PeopleLimit',
            field=models.IntegerField(default=0, verbose_name='关注人数上限'),
        ),
        migrations.AlterField(
            model_name='followmissionplan',
            name='PeopleLimit',
            field=models.IntegerField(default=0, verbose_name='关注人数上限'),
        ),
    ]
