# Generated by Django 2.1.14 on 2019-11-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0059_auto_20191123_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='followmissionplan',
            name='Title',
            field=models.TextField(max_length=150, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='maintenancenumbermissionplan',
            name='Title',
            field=models.TextField(max_length=150, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='scanmissionplan',
            name='Title',
            field=models.TextField(max_length=150, null=True, verbose_name='标题'),
        ),
    ]
