# Generated by Django 2.1.14 on 2019-11-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0061_mobilephone_missionplantemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='Owner',
        ),
        migrations.AddField(
            model_name='works',
            name='Video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.Videos', verbose_name='关联视频'),
        ),
    ]
