# Generated by Django 2.1.14 on 2019-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0062_auto_20191125_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='Describe',
            field=models.TextField(max_length=150, null=True, verbose_name='视频描述'),
        ),
        migrations.AddField(
            model_name='works',
            name='Pic',
            field=models.TextField(max_length=150, null=True, verbose_name='视频封面'),
        ),
    ]
