# Generated by Django 2.1.14 on 2019-11-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0064_tiktokaccount_bingurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiktokaccount',
            old_name='BingURL',
            new_name='BindURL',
        ),
    ]
