# Generated by Django 2.1.14 on 2019-11-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0065_auto_20191125_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokaccount',
            name='BindID',
            field=models.TextField(max_length=150, null=True, verbose_name='绑定主播ID'),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='BindLongURL',
            field=models.TextField(max_length=150, null=True, verbose_name='绑定主播长链接'),
        ),
        migrations.AddField(
            model_name='works',
            name='LongURL',
            field=models.TextField(max_length=150, null=True, verbose_name='长链接'),
        ),
    ]
