# Generated by Django 2.1.14 on 2019-11-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0066_auto_20191125_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokaccount',
            name='BindNickName',
            field=models.TextField(max_length=150, null=True, verbose_name='绑定主播昵称'),
        ),
    ]
