# Generated by Django 2.1.14 on 2019-11-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0067_tiktokaccount_bindnickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='followmission',
            name='FailReason',
            field=models.TextField(null=True, verbose_name='失败原因'),
        ),
        migrations.AddField(
            model_name='maintenancenumbermission',
            name='FailReason',
            field=models.TextField(null=True, verbose_name='失败原因'),
        ),
        migrations.AddField(
            model_name='mutualbrushmission',
            name='FailReason',
            field=models.TextField(null=True, verbose_name='失败原因'),
        ),
        migrations.AddField(
            model_name='scanmission',
            name='FailReason',
            field=models.TextField(null=True, verbose_name='失败原因'),
        ),
        migrations.AddField(
            model_name='videomission',
            name='FailReason',
            field=models.TextField(null=True, verbose_name='失败原因'),
        ),
    ]
