# Generated by Django 2.1.14 on 2019-11-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0068_auto_20191125_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualbrushmission',
            name='Title',
        ),
    ]
