# Generated by Django 2.1.14 on 2019-11-27 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0071_auto_20191127_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaoBaoSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionKey', models.TextField(max_length=500, null=True, verbose_name='授权码')),
                ('Exit_Time', models.BigIntegerField(default=0, verbose_name='授权有效期毫秒数')),
                ('Exit_Date', models.DateTimeField(verbose_name='授权有效期')),
                ('TaoBao_User_ID', models.TextField(max_length=150, null=True, verbose_name='淘宝USERID')),
                ('TaoBao_User_NickName', models.TextField(max_length=150, null=True, verbose_name='淘宝昵称')),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
        ),
    ]
