# Generated by Django 2.1.14 on 2019-11-29 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0073_auto_20191127_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIDDaySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary_Date', models.DateTimeField(verbose_name='统计日期')),
                ('Paid_Order_Count', models.IntegerField(default=0, verbose_name='付款笔数')),
                ('Paid_Pre_Fee', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True, verbose_name='付款预估收入')),
                ('Earn_Pre_Fee', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True, verbose_name='结算预估收入')),
                ('ALIConfig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.ALIConfig', verbose_name='PID')),
            ],
        ),
    ]
