# Generated by Django 2.1.14 on 2019-12-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0075_goods_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='NumOfPlay',
            field=models.IntegerField(default=0, verbose_name='播放'),
        ),
    ]
