# Generated by Django 2.1.14 on 2019-12-03 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0077_auto_20191203_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ALIConfig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.ALIConfig', verbose_name='阿里妈妈配置'),
        ),
    ]
