# Generated by Django 2.1.14 on 2019-12-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0079_order_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='MonthOrder',
            field=models.IntegerField(default=0, verbose_name='本月销量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='TodayOrder',
            field=models.IntegerField(default=0, verbose_name='今天销量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='YestodayOrder',
            field=models.IntegerField(default=0, verbose_name='昨天销量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='Sales',
            field=models.IntegerField(default=0, verbose_name='淘宝销量'),
        ),
    ]
