# Generated by Django 2.1.14 on 2019-12-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0080_auto_20191204_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityDataAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorksCount', models.IntegerField(default=0, verbose_name='视频数量')),
                ('NumOfPraiseGet', models.IntegerField(default=0, verbose_name='喜欢')),
                ('NumOfComments', models.IntegerField(default=0, verbose_name='评论')),
                ('NumOfShare', models.IntegerField(default=0, verbose_name='分享')),
                ('NumOfPlay', models.IntegerField(default=0, verbose_name='播放')),
                ('TodayOrder', models.IntegerField(default=0, verbose_name='今天销量')),
                ('YestodayOrder', models.IntegerField(default=0, verbose_name='昨天销量')),
                ('MonthOrder', models.IntegerField(default=0, verbose_name='本月销量')),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='MonthOrder',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='TodayOrder',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='YestodayOrder',
        ),
        migrations.AddField(
            model_name='commoditydataanalysis',
            name='Goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.Goods', verbose_name='商品'),
        ),
    ]
