# Generated by Django 2.1.14 on 2019-12-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0084_tiktokaccountdataanalysis_summary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokaccountdataanalysis',
            name='VideoIncrease',
        ),
    ]
