# Generated by Django 2.1.14 on 2019-12-05 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0086_videos_videokeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApplyForWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplyDate', models.DateTimeField(verbose_name='申请日期')),
                ('Money', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='申请金额')),
                ('IsPass', models.BooleanField(default=False, verbose_name='是否通过')),
                ('ApproveDate', models.DateTimeField(verbose_name='审批日期')),
                ('Remark', models.TextField(max_length=150, null=True, verbose_name='备注')),
                ('Agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.Agent', verbose_name='代理')),
                ('ApproveUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
        ),
        migrations.CreateModel(
            name='AgentMonthRealityIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SummaryDate', models.DateField(verbose_name='统计日期')),
                ('Money', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='结算金额')),
                ('OrderCount', models.IntegerField(default=0, verbose_name='结算订单量')),
                ('Agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.Agent', verbose_name='代理')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='CalcDate',
            field=models.DateField(null=True, verbose_name='统计日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='IsCalc',
            field=models.BooleanField(default=False, verbose_name='是否已统计'),
        ),
    ]
