# Generated by Django 2.1.14 on 2019-12-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0088_auto_20191206_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentapplyforwithdraw',
            name='IsPass',
            field=models.IntegerField(default=0, verbose_name='是否通过'),
        ),
    ]
