# Generated by Django 2.1.14 on 2019-12-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0092_treasuremission_treasuremissionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='FileName',
            field=models.TextField(max_length=150, null=True, verbose_name='文件名'),
        ),
    ]
