# Generated by Django 2.1.14 on 2019-12-23 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0095_auto_20191211_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchLiveMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(choices=[(0, '待获取'), (1, '已获取'), (2, '已成功结束'), (3, '执行失败')], default=0, verbose_name='状态')),
                ('TargetURL', models.TextField(max_length=150, null=True, verbose_name='目标主播链接')),
                ('CommentText', models.TextField(max_length=500, null=True, verbose_name='评论内容')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('UpdateTime', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('StartTime', models.DateTimeField(verbose_name='任务开始日期')),
                ('EndTime', models.DateTimeField(verbose_name='任务结束日期')),
                ('Priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('FailReason', models.TextField(null=True, verbose_name='失败原因')),
                ('MobilePhone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.MobilePhone', verbose_name='手机ID')),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
        ),
    ]
