# Generated by Django 2.1.14 on 2019-12-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0099_auto_20191226_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='changesignaturemission',
            name='TikTokAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.TikTokAccount', verbose_name='抖音账号'),
        ),
        migrations.AlterField(
            model_name='maintenancenumbermissionkeyword',
            name='Classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.MaintenanceNumberMissionKeywordClassification', verbose_name='类别'),
        ),
    ]
