# Generated by Django 2.1.14 on 2019-12-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0101_auto_20191227_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='changesignaturemission',
            name='TikTokAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.TikTokAccount', verbose_name='抖音账号'),
        ),
    ]
