# Generated by Django 2.1.14 on 2019-12-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0103_auto_20191230_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentmonthrealityincome',
            old_name='Money',
            new_name='OrderMoney',
        ),
        migrations.AddField(
            model_name='agentmonthrealityincome',
            name='MissionMoney',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='任务金额'),
        ),
        migrations.AddField(
            model_name='agentmonthrealityincome',
            name='TotalMoney',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='总金额'),
        ),
    ]
