# Generated by Django 2.1.14 on 2019-12-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0104_auto_20191230_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmonthrealityincome',
            name='MutualBrushMissionCount',
            field=models.IntegerField(default=0, verbose_name='互刷任务量'),
        ),
        migrations.AddField(
            model_name='agentmonthrealityincome',
            name='WatchLiveMissionCount',
            field=models.IntegerField(default=0, verbose_name='观看直播任务量'),
        ),
    ]
