# Generated by Django 2.1.14 on 2020-01-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0111_scanvideolibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanvideolibrary',
            name='Status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
