# Generated by Django 2.1.14 on 2019-11-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0054_auto_20191122_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='followmission',
            name='EndTime',
            field=models.DateTimeField(null=True, verbose_name='任务结束日期'),
        ),
        migrations.AddField(
            model_name='scanmission',
            name='EndTime',
            field=models.DateTimeField(null=True, verbose_name='任务结束日期'),
        ),
        migrations.AlterField(
            model_name='maintenancenumbermission',
            name='EndTime',
            field=models.DateTimeField(null=True, verbose_name='任务结束日期'),
        ),
    ]
