# Generated by Django 2.1.14 on 2019-11-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0058_auto_20191123_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followmission',
            name='FanSex',
        ),
        migrations.RemoveField(
            model_name='followmissionplan',
            name='FanSex',
        ),
        migrations.RemoveField(
            model_name='scanmission',
            name='FanSex',
        ),
        migrations.RemoveField(
            model_name='scanmissionplan',
            name='FanSex',
        ),
        migrations.AddField(
            model_name='followmission',
            name='FanSexIsFemale',
            field=models.BooleanField(default=False, verbose_name='粉丝性别女'),
        ),
        migrations.AddField(
            model_name='followmission',
            name='FanSexIsMale',
            field=models.BooleanField(default=False, verbose_name='粉丝性别男'),
        ),
        migrations.AddField(
            model_name='followmission',
            name='FanSexIsNone',
            field=models.BooleanField(default=False, verbose_name='粉丝性别无'),
        ),
        migrations.AddField(
            model_name='followmissionplan',
            name='FanSexIsFemale',
            field=models.BooleanField(default=False, verbose_name='粉丝性别女'),
        ),
        migrations.AddField(
            model_name='followmissionplan',
            name='FanSexIsMale',
            field=models.BooleanField(default=False, verbose_name='粉丝性别男'),
        ),
        migrations.AddField(
            model_name='followmissionplan',
            name='FanSexIsNone',
            field=models.BooleanField(default=False, verbose_name='粉丝性别无'),
        ),
        migrations.AddField(
            model_name='scanmission',
            name='CommentTextID',
            field=models.TextField(max_length=150, null=True, verbose_name='评论库ID字符串'),
        ),
        migrations.AddField(
            model_name='scanmission',
            name='FanSexIsFemale',
            field=models.BooleanField(default=False, verbose_name='粉丝性别女'),
        ),
        migrations.AddField(
            model_name='scanmission',
            name='FanSexIsMale',
            field=models.BooleanField(default=False, verbose_name='粉丝性别男'),
        ),
        migrations.AddField(
            model_name='scanmission',
            name='FanSexIsNone',
            field=models.BooleanField(default=False, verbose_name='粉丝性别无'),
        ),
        migrations.AddField(
            model_name='scanmissionplan',
            name='CommentTextID',
            field=models.TextField(max_length=150, null=True, verbose_name='评论库ID字符串'),
        ),
        migrations.AddField(
            model_name='scanmissionplan',
            name='FanSexIsFemale',
            field=models.BooleanField(default=False, verbose_name='粉丝性别女'),
        ),
        migrations.AddField(
            model_name='scanmissionplan',
            name='FanSexIsMale',
            field=models.BooleanField(default=False, verbose_name='粉丝性别男'),
        ),
        migrations.AddField(
            model_name='scanmissionplan',
            name='FanSexIsNone',
            field=models.BooleanField(default=False, verbose_name='粉丝性别无'),
        ),
    ]
