# Generated by Django 2.1.14 on 2019-11-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0053_auto_20191122_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancenumbermission',
            name='EndTime',
            field=models.DateTimeField(verbose_name='任务结束日期'),
        ),
    ]
