# Generated by Django 2.1.14 on 2019-11-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0032_remove_mobilephone_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokaccount',
            name='Owner',
        ),
    ]
