# Generated by Django 2.1.14 on 2019-11-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0019_auto_20191115_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancenumbermission',
            name='VideoCategory',
        ),
        migrations.AddField(
            model_name='maintenancenumbermission',
            name='VideoClassifications',
            field=models.ManyToManyField(to='Web.VideoClassification'),
        ),
        migrations.AlterField(
            model_name='followmission',
            name='Status',
            field=models.IntegerField(choices=[(0, '待获取'), (1, '已获取'), (2, '已成功结束'), (3, '执行失败')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='maintenancenumbermission',
            name='Status',
            field=models.IntegerField(choices=[(0, '待获取'), (1, '已获取'), (2, '已成功结束'), (3, '执行失败')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='mutualbrushmission',
            name='Status',
            field=models.IntegerField(choices=[(0, '待获取'), (1, '已获取'), (2, '已成功结束'), (3, '执行失败')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='scanmission',
            name='Status',
            field=models.IntegerField(choices=[(0, '待获取'), (1, '已获取'), (2, '已成功结束'), (3, '执行失败')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='videomission',
            name='Status',
            field=models.IntegerField(choices=[(0, '待获取'), (1, '已获取'), (2, '已成功结束'), (3, '执行失败')], default=0, verbose_name='状态'),
        ),
    ]
