# Generated by Django 2.1.14 on 2019-11-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pass',
            field=models.BooleanField(default=False, verbose_name='是否通过审核'),
        ),
    ]
