# Generated by Django 2.1.14 on 2019-11-16 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_is_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上级'),
        ),
    ]
