# Generated by Django 2.1.14 on 2019-11-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_user_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(default=0, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='true_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='微信'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_nickname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='微信昵称'),
        ),
    ]
