# Generated by Django 2.1.14 on 2019-11-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20191125_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='平台'),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_certification_id_card',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='实名认证身份证'),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_certification_true_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='实名认证姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='平台账号'),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_is_certification',
            field=models.IntegerField(default=0, verbose_name='是否实名认证'),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='平台密码'),
        ),
    ]
