# Generated by Django 2.1.14 on 2019-12-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0085_remove_tiktokaccountdataanalysis_videoincrease'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='VideoKeyword',
            field=models.TextField(max_length=150, null=True, verbose_name='视频话题'),
        ),
    ]
