# Generated by Django 2.1.14 on 2019-11-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0022_auto_20191115_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanmission',
            name='VideoURL',
            field=models.TextField(max_length=500, null=True, verbose_name='视频地址'),
        ),
    ]
