# Generated by Django 2.1.14 on 2019-11-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20191110_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='CommissionPercent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='佣金比例'),
        ),
        migrations.AddField(
            model_name='goods',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/goods/%Y/%m/%d/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='售价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='Sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
