# Generated by Django 2.1.14 on 2019-12-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0100_auto_20191227_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changesignaturemission',
            name='TikTokAccount',
        ),
        migrations.AddField(
            model_name='changesignaturemission',
            name='Describe',
            field=models.TextField(max_length=150, null=True, verbose_name='旧描述'),
        ),
        migrations.AddField(
            model_name='changesignaturemission',
            name='NewDescribe',
            field=models.TextField(max_length=150, null=True, verbose_name='新描述'),
        ),
    ]
