# Generated by Django 2.1.14 on 2019-11-15 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0021_auto_20191115_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='followmission',
            name='CreateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followmission',
            name='UpdateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='maintenancenumbermission',
            name='CreateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancenumbermission',
            name='UpdateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='mutualbrushmission',
            name='CreateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutualbrushmission',
            name='UpdateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='scanmission',
            name='CreateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanmission',
            name='UpdateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='videomission',
            name='CreateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videomission',
            name='UpdateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
