# Generated by Django 2.1.14 on 2019-12-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20191126_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='账户余额'),
        ),
    ]
