# Generated by Django 2.1.14 on 2019-11-16 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0023_auto_20191115_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALIConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NickName', models.TextField(max_length=150, null=True, verbose_name='昵称')),
                ('PID', models.TextField(default='', max_length=150, verbose_name='PID')),
                ('Remark', models.TextField(max_length=150, null=True, verbose_name='备注')),
                ('IsDefault', models.BooleanField(default=False, verbose_name='是否默认')),
                ('Status', models.IntegerField(choices=[(0, '可用'), (1, '不可用')], default=0, verbose_name='状态')),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
        ),
    ]
