# Generated by Django 2.1.14 on 2019-12-04 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0083_tiktokaccountdataanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokaccountdataanalysis',
            name='Summary_Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='统计日期'),
            preserve_default=False,
        ),
    ]
