# Generated by Django 2.1.14 on 2019-11-15 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0017_auto_20191115_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomission',
            name='Video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.Videos', verbose_name='关联视频ID'),
        ),
    ]
