# Generated by Django 2.1.14 on 2019-11-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0040_auto_20191119_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='UpdateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='refund',
            name='UpdateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
