# Generated by Django 2.1.14 on 2019-11-22 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0056_auto_20191122_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=150, null=True, verbose_name='字段')),
                ('Value', models.TextField(max_length=150, null=True, verbose_name='值')),
            ],
        ),
        migrations.CreateModel(
            name='FollowMissionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=150, null=True, verbose_name='任务描述')),
                ('PeopleLimit', models.IntegerField(default=0, verbose_name='刷粉人数上限')),
                ('StartTime', models.DateTimeField(verbose_name='任务开始日期')),
                ('EndTime', models.DateTimeField(null=True, verbose_name='任务结束日期')),
                ('FanSex', models.IntegerField(choices=[(0, '男'), (1, '女'), (1, '无')], default=0, verbose_name='粉丝性别')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceNumberMissionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=150, null=True, verbose_name='任务描述')),
                ('StartTime', models.DateTimeField(verbose_name='任务开始日期')),
                ('EndTime', models.DateTimeField(null=True, verbose_name='任务结束日期')),
            ],
        ),
        migrations.CreateModel(
            name='MissionPlanTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=150, null=True, verbose_name='标题')),
                ('RecordDate', models.DateField(null=True, verbose_name='记录日期')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
        ),
        migrations.CreateModel(
            name='ScanMissionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=150, null=True, verbose_name='任务描述')),
                ('PeopleLimit', models.IntegerField(default=0, verbose_name='刷粉人数上限')),
                ('Interval', models.IntegerField(default=0, verbose_name='间隔')),
                ('StartTime', models.DateTimeField(verbose_name='任务开始日期')),
                ('EndTime', models.DateTimeField(null=True, verbose_name='任务结束日期')),
                ('FanSex', models.IntegerField(choices=[(0, '男'), (1, '女'), (1, '无')], default=0, verbose_name='粉丝性别')),
                ('MissionPlanTemplate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.MissionPlanTemplate', verbose_name='模板ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='followmission',
            name='Interval',
        ),
        migrations.RemoveField(
            model_name='followmission',
            name='TikTokID',
        ),
        migrations.RemoveField(
            model_name='followmission',
            name='TimeLimit',
        ),
        migrations.RemoveField(
            model_name='followmission',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='maintenancenumbermission',
            name='Keyword',
        ),
        migrations.RemoveField(
            model_name='maintenancenumbermission',
            name='TikTokID',
        ),
        migrations.RemoveField(
            model_name='maintenancenumbermission',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='scanmission',
            name='TimeLimit',
        ),
        migrations.RemoveField(
            model_name='scanmission',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='scanmission',
            name='VideoURL',
        ),
        migrations.AddField(
            model_name='followmission',
            name='FanSex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (1, '无')], default=0, verbose_name='粉丝性别'),
        ),
        migrations.AddField(
            model_name='scanmission',
            name='FanSex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (1, '无')], default=0, verbose_name='粉丝性别'),
        ),
        migrations.AlterField(
            model_name='followmission',
            name='MobilePhone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.MobilePhone', verbose_name='手机ID'),
        ),
        migrations.AlterField(
            model_name='maintenancenumbermission',
            name='MobilePhone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.MobilePhone', verbose_name='手机ID'),
        ),
        migrations.AlterField(
            model_name='mutualbrushmission',
            name='MobilePhone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.MobilePhone', verbose_name='手机ID'),
        ),
        migrations.AlterField(
            model_name='scanmission',
            name='MobilePhone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.MobilePhone', verbose_name='手机ID'),
        ),
        migrations.AlterField(
            model_name='videomission',
            name='MobilePhone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.MobilePhone', verbose_name='手机ID'),
        ),
        migrations.AddField(
            model_name='maintenancenumbermissionplan',
            name='MissionPlanTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.MissionPlanTemplate', verbose_name='模板ID'),
        ),
        migrations.AddField(
            model_name='followmissionplan',
            name='MissionPlanTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.MissionPlanTemplate', verbose_name='模板ID'),
        ),
    ]
