# Generated by Django 2.1.14 on 2019-12-31 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_user_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mainuser',
            field=models.BooleanField(default=False, verbose_name='是否是主要用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='usersystem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='顶级用户', to=settings.AUTH_USER_MODEL, verbose_name='顶级用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='上级', to=settings.AUTH_USER_MODEL, verbose_name='上级'),
        ),
    ]
