# Generated by Django 2.1.14 on 2019-12-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0087_auto_20191205_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentapplyforwithdraw',
            name='ApproveDate',
            field=models.DateTimeField(null=True, verbose_name='审批日期'),
        ),
    ]
