# Generated by Django 2.1.14 on 2019-11-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0024_aliconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliconfig',
            name='Category',
            field=models.ManyToManyField(to='Web.GoodClassification'),
        ),
    ]
