# Generated by Django 2.1.14 on 2020-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0110_auto_20200106_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanVideoLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.TextField(default='', verbose_name='关键字')),
                ('VideoURL', models.TextField(default='', verbose_name='目标视频URL')),
                ('UseTime', models.DateTimeField(null=True, verbose_name='使用日期')),
            ],
        ),
    ]
