# Generated by Django 2.1.14 on 2019-11-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0038_auto_20191118_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TB_Paid_Time', models.DateTimeField(null=True)),
                ('TK_Paid_Time', models.DateTimeField(null=True)),
                ('Pay_Price', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('Pub_Share_Fee', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('TK_Earning_Time', models.DateTimeField(null=True)),
                ('ADZone_ID', models.TextField(max_length=150, null=True)),
                ('Pub_Share_Rate', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('unid', models.TextField(max_length=150, null=True)),
                ('Subsidy_Rate', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('TK_Total_Rate', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('Item_Img', models.TextField(max_length=150, null=True)),
                ('Pub_Share_Pre_Fee', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('Alipay_Total_Price', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('Item_Title', models.TextField(max_length=150, null=True)),
                ('Subsidy_Fee', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('Alimama_Share_Fee', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('Trade_Parent_ID', models.TextField(max_length=150, null=True)),
                ('Order_Type', models.TextField(max_length=150, null=True)),
                ('TK_Create_Time', models.DateTimeField(null=True)),
                ('tk_status', models.IntegerField(default=0)),
                ('Item_Price', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('Item_ID', models.TextField(max_length=150, null=True)),
                ('ADZone_Name', models.TextField(max_length=150, null=True)),
                ('Total_Commission_Rate', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('Item_Link', models.TextField(max_length=500, null=True)),
                ('Site_ID', models.TextField(max_length=150, null=True)),
                ('Income_Rate', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('Total_Commission_Fee', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TB_Trade_Parent_ID', models.TextField(max_length=150, null=True)),
                ('TK_Subsidy_Fee_Refund3rd_Pub', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('TK_Commission_Fee_Refund3rd_Pub', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('TK_Subsidy_Fee_Refund_Pub', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('TK_Commission_Fee_Refund_Pub', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('TK_Refund_Suit_Time', models.DateTimeField(null=True)),
                ('TK_Refund_Time', models.DateTimeField(null=True)),
                ('Earning_Time', models.DateTimeField(null=True)),
                ('TB_Trade_Create_Time', models.DateTimeField(null=True)),
                ('refund_status', models.IntegerField(default=0)),
                ('TB_Auction_Title', models.TextField(max_length=150, null=True)),
                ('Refund_Fee', models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.Order', verbose_name='订单ID')),
            ],
        ),
    ]
