# Generated by Django 2.1.14 on 2019-11-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_auto_20191111_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='Pic',
        ),
        migrations.AddField(
            model_name='goods',
            name='Pic1',
            field=models.TextField(null=True, verbose_name='图片1'),
        ),
        migrations.AddField(
            model_name='goods',
            name='Pic2',
            field=models.TextField(null=True, verbose_name='图片2'),
        ),
        migrations.AddField(
            model_name='goods',
            name='Pic3',
            field=models.TextField(null=True, verbose_name='图片3'),
        ),
        migrations.AddField(
            model_name='goods',
            name='Pic4',
            field=models.TextField(null=True, verbose_name='图片4'),
        ),
        migrations.AddField(
            model_name='goods',
            name='Pic5',
            field=models.TextField(null=True, verbose_name='图片5'),
        ),
    ]
