# Generated by Django 2.1.14 on 2019-11-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0069_remove_mutualbrushmission_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='unid',
            new_name='Flow_Source',
        ),
        migrations.AddField(
            model_name='order',
            name='Alimama_Rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Click_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Deposit_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Item_Category_Name',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Item_Num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Pub_ID',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Refund_Tag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Seller_Nick',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Seller_Shop_Title',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Site_Name',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Subsidy_Type',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='TB_Deposit_Time',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='TK_Commission_Fee_For_Media_Platform',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='TK_Commission_Pre_Fee_For_Media_Platform',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='TK_Commission_Rate_For_Media_Platform',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='TK_Deposit_Time',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='TK_Order_Role',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='order',
            name='Terminal_Type',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Trade_ID',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
