# Generated by Django 2.1.14 on 2019-12-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0093_videos_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokaccountdataanalysis',
            name='NumOfComments',
            field=models.IntegerField(default=0, verbose_name='总评论量'),
        ),
        migrations.AddField(
            model_name='tiktokaccountdataanalysis',
            name='NumOfCommentsIncrease',
            field=models.IntegerField(default=0, verbose_name='评论增量'),
        ),
    ]
