# Generated by Django 2.1.14 on 2019-12-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0082_auto_20191204_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokAccountDataAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attention', models.IntegerField(default=0, verbose_name='关注')),
                ('Fans', models.IntegerField(default=0, verbose_name='粉丝')),
                ('Praise', models.IntegerField(default=0, verbose_name='赞')),
                ('Video', models.IntegerField(default=0, verbose_name='作品数')),
                ('NumOfPraiseToOther', models.IntegerField(default=0, verbose_name='喜欢')),
                ('TotalNumOfPlay', models.IntegerField(default=0, verbose_name='总播放量')),
                ('FirstWorkNumOfPlay', models.IntegerField(default=0, verbose_name='作品1播放量')),
                ('AttentionIncrease', models.IntegerField(default=0, verbose_name='关注增量')),
                ('FansIncrease', models.IntegerField(default=0, verbose_name='粉丝增量')),
                ('PraiseIncrease', models.IntegerField(default=0, verbose_name='赞增量')),
                ('VideoIncrease', models.IntegerField(default=0, verbose_name='作品数增量')),
                ('NumOfPraiseToOtherIncrease', models.IntegerField(default=0, verbose_name='喜欢增量')),
                ('TotalNumOfPlayIncrease', models.IntegerField(default=0, verbose_name='总播放量增量')),
                ('FirstWorkNumOfPlayIncrease', models.IntegerField(default=0, verbose_name='作品1播放量增量')),
                ('TikTokAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.TikTokAccount', verbose_name='抖音账号')),
            ],
        ),
    ]
