# Generated by Django 2.1.14 on 2019-11-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0042_auto_20191120_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokAccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=150, verbose_name='分组名字')),
            ],
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='Area',
            field=models.TextField(max_length=150, null=True, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='Classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.MaintenanceNumberMissionKeywordClassification', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='IP',
            field=models.TextField(max_length=150, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='IsOnline',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='Remark',
            field=models.TextField(max_length=150, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tiktokaccount',
            name='ShowWindowExists',
            field=models.BooleanField(default=False, verbose_name='是否电商'),
        ),
        migrations.AddField(
            model_name='tiktokaccount',
            name='Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.TikTokAccountGroup', verbose_name='分组'),
        ),
    ]
