# Generated by Django 2.1.14 on 2019-11-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.TextField(default='', max_length=150, verbose_name='邀请码'),
        ),
    ]
