# Generated by Django 2.1.14 on 2020-01-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0112_scanvideolibrary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanmission',
            name='IsDirectional',
            field=models.BooleanField(default=False, verbose_name='是否定向'),
        ),
    ]
