# Generated by Django 2.1.14 on 2019-12-31 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0106_auto_20191231_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUserRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TopUserRelationsLeader', to=settings.AUTH_USER_MODEL, verbose_name='上级')),
                ('Subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TopUserRelationsSubscriber', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
