# Generated by Django 2.1.14 on 2019-11-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0039_order_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tk_status',
            new_name='TK_Status',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='refund_status',
            new_name='Refund_Status',
        ),
    ]
