# Generated by Django 2.1.14 on 2019-11-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_auto_20191113_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='URL',
            field=models.FileField(upload_to='videos/%Y/%m/%d/', verbose_name='视频文件'),
        ),
    ]
