# Generated by Django 2.1.14 on 2019-12-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0089_auto_20191206_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MissionName', models.TextField(max_length=150, null=True, verbose_name='任务名')),
                ('MissionID', models.IntegerField(default=0, verbose_name='任务id')),
                ('Status', models.IntegerField(choices=[(0, '待获取'), (1, '已获取'), (2, '已成功结束'), (3, '执行失败')], default=0, verbose_name='状态')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('StartTime', models.DateTimeField(verbose_name='任务开始日期')),
                ('EndTime', models.DateTimeField(null=True, verbose_name='任务结束日期')),
                ('FailReason', models.TextField(null=True, verbose_name='失败原因')),
                ('MobilePhone_id', models.IntegerField(default=0, verbose_name='设备id')),
                ('NickName', models.TextField(max_length=150, null=True, verbose_name='抖音账号')),
            ],
            options={
                'db_table': 'VAllMissions',
                'managed': False,
            },
        ),
    ]
