# Generated by Django 2.1.14 on 2019-12-03 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0076_works_numofplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokAccountDaySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary_Date', models.DateField(verbose_name='统计日期')),
                ('Attention', models.IntegerField(default=0, verbose_name='关注')),
                ('Fans', models.IntegerField(default=0, verbose_name='粉丝')),
                ('Praise', models.IntegerField(default=0, verbose_name='赞')),
                ('Video', models.IntegerField(default=0, verbose_name='作品数')),
                ('NumOfPraiseToOther', models.IntegerField(default=0, verbose_name='喜欢')),
                ('TikTokAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.TikTokAccount', verbose_name='抖音账号')),
            ],
        ),
        migrations.CreateModel(
            name='WorksDaySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary_Date', models.DateField(verbose_name='统计日期')),
                ('NumOfPraiseGet', models.IntegerField(default=0, verbose_name='喜欢')),
                ('NumOfComments', models.IntegerField(default=0, verbose_name='评论')),
                ('NumOfShare', models.IntegerField(default=0, verbose_name='分享')),
                ('NumOfPlay', models.IntegerField(default=0, verbose_name='播放')),
            ],
        ),
        migrations.AddField(
            model_name='works',
            name='UploadTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='视频上传日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piddaysummary',
            name='Summary_Date',
            field=models.DateField(verbose_name='统计日期'),
        ),
        migrations.AddField(
            model_name='worksdaysummary',
            name='Work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.Works', verbose_name='抖音视频'),
        ),
    ]
