# Generated by Django 2.1.14 on 2019-11-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0049_auto_20191121_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlibrary',
            name='Owner',
        ),
        migrations.AlterField(
            model_name='mutualbrushmission',
            name='CommentText',
            field=models.TextField(max_length=500, null=True, verbose_name='评论内容'),
        ),
    ]
