# Generated by Django 2.1.14 on 2019-11-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_auto_20191112_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=150, verbose_name='标题')),
                ('URL', models.TextField(max_length=150, verbose_name='视频文件位置')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('Remark', models.TextField(max_length=150, null=True, verbose_name='备注')),
            ],
        ),
        migrations.RemoveField(
            model_name='works',
            name='WorkClassifications',
        ),
        migrations.RenameModel(
            old_name='WorkClassification',
            new_name='VideoClassification',
        ),
        migrations.AddField(
            model_name='videos',
            name='VideoClassifications',
            field=models.ManyToManyField(to='Web.VideoClassification'),
        ),
    ]
