# Generated by Django 2.1.14 on 2019-11-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20191110_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(choices=[(0, '待执行'), (10, '已开始未结束'), (11, '执行失败'), (20, '已结束')], default=0, verbose_name='状态')),
                ('FeedBackMessage', models.TextField(max_length=200, null=True, verbose_name='反馈信息')),
                ('TaskType', models.IntegerField(choices=[(1, '上传视频'), (2, '浏览视频'), (3, '刷粉任务'), (4, '互刷任务')], default=1, verbose_name='类型')),
                ('TaskData', models.TextField(max_length=500, null=True, verbose_name='任务信息')),
            ],
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='Enable',
            field=models.BooleanField(default=False, verbose_name='是否可用'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='StatusInfo',
            field=models.TextField(max_length=150, null=True, verbose_name='状态信息'),
        ),
        migrations.AddField(
            model_name='task',
            name='MobilePhoneID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.MobilePhone', verbose_name='手机ID'),
        ),
    ]
