# Generated by Django 2.1.14 on 2019-12-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0081_auto_20191204_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksDataAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumOfPraiseGet', models.IntegerField(default=0, verbose_name='点赞量')),
                ('NumOfComments', models.IntegerField(default=0, verbose_name='评论量')),
                ('NumOfShare', models.IntegerField(default=0, verbose_name='分享量')),
                ('NumOfPlay', models.IntegerField(default=0, verbose_name='播放量')),
            ],
        ),
        migrations.AlterField(
            model_name='commoditydataanalysis',
            name='NumOfPraiseGet',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='works',
            name='NumOfComments',
            field=models.IntegerField(default=0, verbose_name='评论量'),
        ),
        migrations.AlterField(
            model_name='works',
            name='NumOfPlay',
            field=models.IntegerField(default=0, verbose_name='播放量'),
        ),
        migrations.AlterField(
            model_name='works',
            name='NumOfPraiseGet',
            field=models.IntegerField(default=0, verbose_name='点赞量'),
        ),
        migrations.AlterField(
            model_name='works',
            name='NumOfShare',
            field=models.IntegerField(default=0, verbose_name='分享量'),
        ),
        migrations.AlterField(
            model_name='worksdaysummary',
            name='NumOfComments',
            field=models.IntegerField(default=0, verbose_name='评论量'),
        ),
        migrations.AlterField(
            model_name='worksdaysummary',
            name='NumOfPlay',
            field=models.IntegerField(default=0, verbose_name='播放量'),
        ),
        migrations.AlterField(
            model_name='worksdaysummary',
            name='NumOfPraiseGet',
            field=models.IntegerField(default=0, verbose_name='点赞量'),
        ),
        migrations.AlterField(
            model_name='worksdaysummary',
            name='NumOfShare',
            field=models.IntegerField(default=0, verbose_name='分享量'),
        ),
        migrations.AddField(
            model_name='worksdataanalysis',
            name='Works',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.Works', verbose_name='作品'),
        ),
    ]
