# Generated by Django 2.1.14 on 2019-11-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0033_remove_tiktokaccount_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='CouponURL',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='PIDURL',
        ),
        migrations.AddField(
            model_name='videomission',
            name='CouponURL',
            field=models.TextField(max_length=500, null=True, verbose_name='优惠券URL'),
        ),
        migrations.AddField(
            model_name='videomission',
            name='PIDURL',
            field=models.TextField(max_length=500, null=True, verbose_name='推广URL'),
        ),
        migrations.AlterField(
            model_name='videomission',
            name='GoodURL',
            field=models.TextField(max_length=500, null=True, verbose_name='最终商品地址'),
        ),
    ]
