# Generated by Django 2.1.14 on 2019-12-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0094_auto_20191211_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiktokaccountdataanalysis',
            old_name='NumOfComments',
            new_name='TotalNumOfComments',
        ),
        migrations.RenameField(
            model_name='tiktokaccountdataanalysis',
            old_name='NumOfCommentsIncrease',
            new_name='TotalNumOfCommentsIncrease',
        ),
    ]
