# Generated by Django 2.1.14 on 2019-11-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0025_aliconfig_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliconfig',
            name='LASTPID',
            field=models.TextField(default='', max_length=150, verbose_name='LASTPID'),
        ),
    ]
