# Generated by Django 2.1.14 on 2019-11-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0070_auto_20191126_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomission',
            name='CouponURL',
        ),
        migrations.RemoveField(
            model_name='videomission',
            name='PIDURL',
        ),
    ]
