# Generated by Django 2.1.14 on 2019-11-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0046_auto_20191120_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokaccount',
            name='TaoBao_PID',
        ),
    ]
