# Generated by Django 2.1.14 on 2019-11-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0011_auto_20191113_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='Title',
            field=models.TextField(max_length=150, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='URL',
            field=models.FileField(null=True, upload_to='videos/%Y/%m/%d/', verbose_name='视频文件'),
        ),
    ]
