# Generated by Django 2.1.14 on 2019-12-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0102_changesignaturemission_tiktokaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualbrushmission',
            name='CalcDate',
            field=models.DateTimeField(null=True, verbose_name='任务收益统计日期'),
        ),
        migrations.AddField(
            model_name='mutualbrushmission',
            name='IsCalc',
            field=models.BooleanField(default=False, verbose_name='任务收益是否已统计'),
        ),
        migrations.AddField(
            model_name='mutualbrushmission',
            name='MissionIncome',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='任务收益'),
        ),
        migrations.AddField(
            model_name='watchlivemission',
            name='CalcDate',
            field=models.DateTimeField(null=True, verbose_name='任务收益统计日期'),
        ),
        migrations.AddField(
            model_name='watchlivemission',
            name='IsCalc',
            field=models.BooleanField(default=False, verbose_name='任务收益是否已统计'),
        ),
        migrations.AddField(
            model_name='watchlivemission',
            name='MissionIncome',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='任务收益'),
        ),
    ]
