# Generated by Django 2.1.14 on 2020-01-06 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0109_auto_20200106_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditydataanalysis',
            name='CommodityOwner',
        ),
        migrations.RemoveField(
            model_name='tiktokaccountdataanalysis',
            name='AccountOwner',
        ),
        migrations.RemoveField(
            model_name='worksdataanalysis',
            name='WorkOwner',
        ),
        migrations.AlterField(
            model_name='commoditydataanalysis',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
        migrations.AlterField(
            model_name='tiktokaccountdataanalysis',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
        migrations.AlterField(
            model_name='worksdataanalysis',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
    ]
