# Generated by Django 2.1.14 on 2019-11-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0063_auto_20191125_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokaccount',
            name='BingURL',
            field=models.TextField(max_length=150, null=True, verbose_name='绑定主播URL'),
        ),
    ]
