# Generated by Django 2.1.14 on 2019-12-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0096_watchlivemission'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlivemission',
            name='CommentTimes',
            field=models.IntegerField(default=0, verbose_name='评论次数'),
        ),
    ]
