# Generated by Django 2.1.14 on 2019-11-16 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0030_auto_20191116_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliconfig',
            name='IsDefault',
        ),
        migrations.RemoveField(
            model_name='aliconfig',
            name='Owner',
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='ALIConfig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.ALIConfig', verbose_name='阿里妈妈配置'),
        ),
    ]
