# Generated by Django 2.1.14 on 2019-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0048_remove_mobilephone_isonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='HeartBeat',
            field=models.DateTimeField(null=True, verbose_name='心跳时间'),
        ),
    ]
