# Generated by Django 2.1.14 on 2019-11-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='SysID',
            field=models.CharField(max_length=64, verbose_name='GUID'),
        ),
    ]
