# Generated by Django 2.1.14 on 2019-11-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0047_remove_tiktokaccount_taobao_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilephone',
            name='IsOnline',
        ),
    ]
