# Generated by Django 2.1.14 on 2019-11-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0060_auto_20191123_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='MissionPlanTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.MissionPlanTemplate', verbose_name='计划任务模板'),
        ),
    ]
